### ISSUE TITLE
Add endpoint to search curricula

### ISSUE THREAD

**Issue by tinmn9088** [fenix23707/uis-backend#101]
__GET__ `/api/curriculums/search` with optional URL parameters:
* _size_: number
* _sort_: number
* _admissionYearBegin_: number
* _admissionYearEnd_: number
* _approvalDateBegin_: date
* _approvalDateEnd_: date

**Comment by fenix23707** [comment]
implemented with following approach

![Image](https://github.com/fenix23707/uis-backend/assets/81484108/fe585a8d-1478-42ba-b6c9-ef3cb53a0898)
